"""Changed the datatype of Emotion_Id and Model_Id from uuid to string10

Revision ID: 02a0367389f3
Revises: 235feecf7afd
Create Date: 2025-10-01 16:50:42.620760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # <--- ADD THIS LINE


# revision identifiers, used by Alembic.
revision: str = '02a0367389f3'
down_revision: Union[str, Sequence[str], None] = '235feecf7afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Drop FK for Emotion_Id
    op.drop_constraint('Calls_Emotion_Id_fkey', 'Calls', type_='foreignkey')

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Emotions', 'Emotion_Id',
               existing_type=sa.UUID(),
               type_=sa.String(length=10),
               existing_nullable=False)
    
    # Change Emotion_Id FK type in 'Calls' table
    op.alter_column('Calls', 'Emotion_Id', 
           existing_type=postgresql.UUID(as_uuid=True),
           type_=sa.String(length=10),
           postgresql_using='CAST("Emotion_Id" AS VARCHAR(10))')
    # ### end Alembic commands ###

    # Recreate FK for Emotion_Id
    op.create_foreign_key('Calls_Emotion_Id_fkey', 'Calls', 'Emotions', 
                      ['Emotion_Id'], ['Emotion_Id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Emotions', 'Emotion_Id',
               existing_type=sa.String(length=10),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
