"""drop call_attempts table

Revision ID: 07384d990e9c
Revises: 20251208_add_phone_to_targets
Create Date: 2025-12-11 02:17:59.783327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07384d990e9c'
down_revision: Union[str, Sequence[str], None] = '20251208_add_phone_to_targets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Call_Attempts')
    op.drop_constraint(op.f('Calls_Call_Sid_key'), 'Calls', type_='unique')
    op.alter_column('Targets', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Targets', 'Roll_No',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Targets', 'Department_Name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Targets', 'Program',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Targets', 'Program',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Targets', 'Department_Name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Targets', 'Roll_No',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Targets', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(op.f('Calls_Call_Sid_key'), 'Calls', ['Call_Sid'], postgresql_nulls_not_distinct=False)
    op.create_table('Call_Attempts',
    sa.Column('Attempt_Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Call_Id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('Call_Sid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Attempt_Number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Scheduled_Time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('Started_Time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('End_Time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('Duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Status', postgresql.ENUM('Awaiting Schedule', 'Message Not Conveyed', 'Message Conveyed But Not Processed', 'Message Conveyed And Processed', 'Message Conveyed And Processing Failed', name='call_status_enum'), autoincrement=False, nullable=True),
    sa.Column('Recording_Url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Call_Id'], ['Calls.Call_Id'], name=op.f('Call_Attempts_Call_Id_fkey')),
    sa.PrimaryKeyConstraint('Attempt_Id', name=op.f('Call_Attempts_pkey')),
    sa.UniqueConstraint('Call_Id', 'Attempt_Number', name=op.f('uq_call_attempt_number'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Call_Sid', name=op.f('Call_Attempts_Call_Sid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Recording_Url', name=op.f('Call_Attempts_Recording_Url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
