"""Add back Prev_Attempt_Scheduled_Time column to Calls

Revision ID: 235feecf7afd
Revises: 599119ac6275
Create Date: 2025-09-30 23:43:26.184738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235feecf7afd'
down_revision: Union[str, Sequence[str], None] = '599119ac6275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calls', sa.Column('Prev_Attempt_Scheduled_Time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Calls', 'Prev_Attempt_Scheduled_Time')
    # ### end Alembic commands ###
