"""Make call_sid nullable, drop recording_url unique, add uq_target_scheduled_time

Revision ID: 2d52d6be2549
Revises: 02a0367389f3
Create Date: 2025-10-06 03:49:51.607857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d52d6be2549'
down_revision: Union[str, Sequence[str], None] = '02a0367389f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Calls', 'Call_Sid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('Calls_Recording_Url_key'), 'Calls', type_='unique')
    op.create_unique_constraint('uq_target_scheduled_time', 'Calls', ['Target_Id', 'Scheduled_Time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_target_scheduled_time', 'Calls', type_='unique')
    op.create_unique_constraint(op.f('Calls_Recording_Url_key'), 'Calls', ['Recording_Url'], postgresql_nulls_not_distinct=False)
    op.alter_column('Calls', 'Call_Sid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
