"""create all base tables

Revision ID: 40ec0bfb9fa4
Revises: 
Create Date: 2025-09-30 20:22:58.570452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ec0bfb9fa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admins',
    sa.Column('Admin_Id', sa.UUID(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Admin_Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Emotions',
    sa.Column('Emotion_Id', sa.UUID(), nullable=False),
    sa.Column('Emotion', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Emotion_Id'),
    sa.UniqueConstraint('Emotion')
    )
    op.create_table('Error_Logs',
    sa.Column('Logs_Id', sa.UUID(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Error_Type', sa.String(), nullable=True),
    sa.Column('Error_Message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Logs_Id')
    )
    op.create_table('Models',
    sa.Column('Model_Id', sa.UUID(), nullable=False),
    sa.Column('Model_Name', sa.String(), nullable=True),
    sa.Column('Model_Version', sa.String(), nullable=True),
    sa.Column('Model_Details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Model_Id')
    )
    op.create_table('Targets',
    sa.Column('Target_Id', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Street', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('State', sa.String(), nullable=True),
    sa.Column('Zip_Code', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('Phone_No', sa.String(), nullable=True),
    sa.Column('Batch', sa.Integer(), nullable=True),
    sa.Column('Department_Name', sa.Enum('Computer Science', 'Mechanical', 'Chemical', 'Civil', 'Biological', 'Electrical', 'Chemistry', 'Mathematics', 'Physics', 'Earth Sciences', 'Humanities and Social Sciences', name='department_name_enum'), nullable=True),
    sa.Column('Program', sa.String(), nullable=True),
    sa.Column('Semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Target_Id'),
    sa.UniqueConstraint('Phone_No')
    )
    op.create_table('Calls',
    sa.Column('Call_Id', sa.UUID(), nullable=False),
    sa.Column('Call_Sid', sa.String(length=100), nullable=False),
    sa.Column('Target_Id', sa.UUID(), nullable=True),
    sa.Column('Model_Id', sa.UUID(), nullable=True),
    sa.Column('Retries_Count', sa.Integer(), nullable=True),
    sa.Column('Scheduled_Time', sa.DateTime(), nullable=True),
    sa.Column('Started_Time', sa.DateTime(), nullable=True),
    sa.Column('End_Time', sa.DateTime(), nullable=True),
    sa.Column('Next_Retry_Time', sa.DateTime(), nullable=True),
    sa.Column('Emotion_Id', sa.UUID(), nullable=True),
    sa.Column('Status', sa.Enum('Awaiting Schedule', 'Message Not Conveyed', 'Message Conveyed But Not Processed', 'Message Conveyed And Processed', 'Message Conveyed And Processing Failed', name='call_status_enum'), nullable=True),
    sa.Column('Duration', sa.Integer(), nullable=True),
    sa.Column('Recording_Url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['Emotion_Id'], ['Emotions.Emotion_Id'], ),
    sa.ForeignKeyConstraint(['Model_Id'], ['Models.Model_Id'], ),
    sa.ForeignKeyConstraint(['Target_Id'], ['Targets.Target_Id'], ),
    sa.PrimaryKeyConstraint('Call_Id'),
    sa.UniqueConstraint('Call_Sid'),
    sa.UniqueConstraint('Recording_Url')
    )
    op.create_table('Call_Attempts',
    sa.Column('Attempt_Id', sa.UUID(), nullable=False),
    sa.Column('Call_Id', sa.UUID(), nullable=True),
    sa.Column('Call_Sid', sa.String(length=100), nullable=False),
    sa.Column('Attempt_Number', sa.Integer(), nullable=False),
    sa.Column('Scheduled_Time', sa.DateTime(), nullable=True),
    sa.Column('Started_Time', sa.DateTime(), nullable=True),
    sa.Column('End_Time', sa.DateTime(), nullable=True),
    sa.Column('Duration', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Enum('Awaiting Schedule', 'Message Not Conveyed', 'Message Conveyed But Not Processed', 'Message Conveyed And Processed', 'Message Conveyed And Processing Failed', name='call_status_enum'), nullable=True),
    sa.Column('Recording_Url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['Call_Id'], ['Calls.Call_Id'], ),
    sa.PrimaryKeyConstraint('Attempt_Id'),
    sa.UniqueConstraint('Call_Id', 'Attempt_Number', name='uq_call_attempt_number'),
    sa.UniqueConstraint('Call_Sid'),
    sa.UniqueConstraint('Recording_Url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Call_Attempts')
    op.drop_table('Calls')
    op.drop_table('Targets')
    op.drop_table('Models')
    op.drop_table('Error_Logs')
    op.drop_table('Emotions')
    op.drop_table('Admins')
    # ### end Alembic commands ###
