"""Updated call_status_eum to 7 statuses

Revision ID: 93e2360b1abd
Revises: b292cf8bfab2
Create Date: 2025-12-29 21:37:58.310388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e2360b1abd'
down_revision: Union[str, Sequence[str], None] = 'b292cf8bfab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rename old enum type
    op.execute('ALTER TYPE call_status_enum RENAME TO call_status_enum_old;')

    # Create new enum type
    op.execute('''
        CREATE TYPE call_status_enum AS ENUM (
            'Call Scheduled', 'failed', 'busy', 'no-answer',
            'Message Not Conveyed', 'Message Conveyed But Not Processed', 'Message Conveyed And Processed'
        );
    ''')

    # Change column type to TEXT
    op.execute('ALTER TABLE "Calls" ALTER COLUMN "Status" TYPE TEXT;')

    # Update data
    op.execute("UPDATE \"Calls\" SET \"Status\" = 'Call Scheduled' WHERE \"Status\" = 'Awaiting Schedule';")

    # Change column type to new enum
    op.execute('ALTER TABLE "Calls" ALTER COLUMN "Status" TYPE call_status_enum USING "Status"::call_status_enum;')

    # Drop old enum type
    op.execute('DROP TYPE call_status_enum_old;')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
