"""Call Status - 'Message Processing Failed' Added

Revision ID: a087637db8b4
Revises: 2d52d6be2549
Create Date: 2025-10-08 15:42:38.198965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a087637db8b4'
down_revision: Union[str, Sequence[str], None] = '2d52d6be2549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
