"""rename flagged_since timestamp to Call_Scheduled_DateTime

Revision ID: b292cf8bfab2
Revises: 86f18959926f
Create Date: 2025-12-23 13:00:13.848686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b292cf8bfab2'
down_revision: Union[str, Sequence[str], None] = '86f18959926f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FlaggedTargets', sa.Column('Call_Scheduled_DateTime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('FlaggedTargets', 'Flagged_Since')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FlaggedTargets', sa.Column('Flagged_Since', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('FlaggedTargets', 'Call_Scheduled_DateTime')
    # ### end Alembic commands ###
