"""Removing Stream SID from Calls Table

Revision ID: cbcb7808780f
Revises: 93e2360b1abd
Create Date: 2025-12-30 00:24:34.272157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcb7808780f'
down_revision: Union[str, Sequence[str], None] = '93e2360b1abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Calls', 'Stream_Sid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calls', sa.Column('Stream_Sid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
