"""add_password_reset_tokens_table

Revision ID: f122396d2b6a
Revises: cbcb7808780f
Create Date: 2026-01-21 10:55:33.982321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f122396d2b6a'
down_revision: Union[str, Sequence[str], None] = 'cbcb7808780f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Password_Reset_Tokens',
    sa.Column('Token_Id', sa.UUID(), nullable=False),
    sa.Column('Admin_Id', sa.UUID(), nullable=False),
    sa.Column('Token', sa.String(length=255), nullable=False),
    sa.Column('Created_At', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Expires_At', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin_Id'], ['Admins.Admin_Id'], ),
    sa.PrimaryKeyConstraint('Token_Id'),
    sa.UniqueConstraint('Token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Password_Reset_Tokens')
    # ### end Alembic commands ###
